language: java
jdk:
- openjdk8
script: ant build

addons:
sonarcloud:
organization: "daxwagner"
token:
  secure: "Aq390EJQcJ4pzZc4/kUU96muPIcuDsd1+QG6dK7trenfxt25b2Lpxnt9s/aqg1lW+AOPoAXVf26+aSrkgIgZIE4Wpsq7NnhqTd6YNii4UqXNki0/6g+qIodHcwBqFCweXt0H6KQvSquMqqhJ3eN6T8NXGrty1wMEG6MoLYY4+Y4EtnZcJ+nqRz/F5SHSAtj9cGGp5mdp7P0War7yjApOJgK4nMxJiGF4/igOatiDHSnB/4WTuqBfonLmWi8dWXSGJvJdpsUUI3RZIbLXm7Pnth/4Z6DI2GPKXZcoANCqnOMpOxGsqXKfqqEAdAzjY4dd3bJZHTP/ook/CX429NimZZzlcRRWjO3UMqjnA1vUPBEGU2GnRptQFLlW82aXyLXj91PVNKySQTv51BW+A6PmYKgNOSjJPopVUgwYwLX4EZQw59RkSc8QwazsCNOfuPKTqPt/EenNUcNovm+YRbGZtxsMC1VpSsAUG0D+lh0Y/4A5kmWV1DcvVJ+QZ4U2UPZ8RUcBwUyw4TCHhKANO6U6x7Bh8CyGQKT9m7oNEPKfhVamrAUtIt1CK8v1W3Wurtjy3JEprcrkvTs5TzDPzr7OUzlKRNi5I9TSoQTi1gqKOkJsVXx0ATn3DKVPdyQjYKne1YYuTmMeSqV/ueMh2sGcPxuSGhZb7CUL2JNexBdr5EI="
script:
-ant build
-sonar-scanner